# Generated by Django 6.0 on 2025-12-28 17:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failure_type', models.CharField(max_length=50)),
                ('severity', models.CharField(max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='FrameStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_code', models.CharField(max_length=50, unique=True)),
                ('supplier_name', models.CharField(max_length=100)),
                ('material', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='complaints/')),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='qc.complaint')),
            ],
        ),
        migrations.CreateModel(
            name='FrameVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('color', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('APPROVED', 'Approved'), ('WATCH', 'Watch'), ('HOLD', 'Hold'), ('PULLED', 'Pulled')], default='APPROVED', max_length=10)),
                ('qc_score_cached', models.IntegerField(default=100)),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qc.framestyle')),
            ],
        ),
        migrations.AddField(
            model_name='complaint',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qc.framevariant'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qc.store'),
        ),
    ]
